dist: trusty # Travis CI does not currently (2018-03-18) support a more recent Ubuntu
language: generic
before_install:
  - sudo add-apt-repository ppa:openscad/releases -y # Needed, as we're on a really old Ubuntu
  - sudo apt-get -qq update
  - sudo apt-get -qq purge fglrx
  - sudo apt-get install -y openscad mesa-utils
env:
  global:
    - DISPLAY=:99 # xvfb will start on :99 per default
script:
  - ./lint --verbose
  # xvfb-run from Travis CI fails to bring up working 3D environment,
  # so we resort to starting xvfb manually.
  - sh -e /etc/init.d/xvfb start
  - sleep 2 # Give xvfb some time to come up
  - ./test --verbose
